name: SonarQube Scan 

on:
  workflow_dispatch:

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run SonarQube Scan
    - name: SonarQube Scan
      # uses: sonarsource/sonarqube-scan-action@v3
      # with:
      #   projectBaseDir: ./
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
      run: |
          # Extract the sonar.projectKey from the sonar-project.properties file
          PROJECT_KEY=$(grep -Po '(?<=^sonar.projectKey=).*' sonar-project.properties)
          PROJECT_NAME=$(grep -Po '(?<=^sonar.projectName=).*' sonar-project.properties)
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.projectName=$PROJECT_NAME
